"""D2 --- is the cone  C = A_inf(non-negative solutions)  pointed?

Gap D of the manuscript was reduced (Section 7) to D1 (A_inf(b) != 0)
and D2 (the cone C is pointed: C cap -C = {0}).  C is generated by the
windowed-coefficient limits A_inf(e^(r)) of the basis solutions e^(r):
the strategy-ALL recursion started from initial data delta_r on [0,M],
then run by the recursion for n > M.  Every non-negative solution is a
non-negative combination of e^(0),...,e^(M), so

    C = cone{ A_inf(e^(r)) : r = 0,...,M }.

D2 holds iff these M+1 generators lie in an OPEN half-plane -- i.e.
the largest gap between their (sorted, cyclic) arguments exceeds pi.
If instead the generators wind around the origin, C is not pointed,
D2 is FALSE, -A_inf(b) lies in C, and the cone argument for Gap D
collapses.

Suspicion under test: the recursion is not scale-invariant, so a
"delta at r" should oscillate with an r-dependent phase ~ omega*log r;
as r ranges over several periods the generators should wind around.

Run from the repository root:
    .venv/bin/python simulation/d2_cone.py
"""

from __future__ import annotations

import sys
from fractions import Fraction
from math import pi as PI
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from b_asymptotics import b_sequence  # noqa: E402
from renorm_validation import (  # noqa: E402
    chi, local_coefficient, aitken, HALF_WIDTH,
)

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from mpmath import mp, mpf, log, pi, arg, floor  # noqa: E402

mp.dps = 50

M = 10            # basis solutions e^(0),...,e^(M)
N_MAX = 900       # recursion depth


def basis_solution(n_max, p, m_cut, r):
    """Strategy-ALL solution with initial data delta_r on [0, m_cut],
    then the recursion g_n = sum_{j<n} P(Bin(n,q)=j) g_j for n > m_cut."""
    one = mpf(1)
    q = one - p
    p_pow = [one]
    q_pow = [one]
    for _ in range(n_max):
        p_pow.append(p_pow[-1] * p)
        q_pow.append(q_pow[-1] * q)
    g = [mpf(0)] * (n_max + 1)
    g[r] = one
    for n in range(m_cut + 1, n_max + 1):
        total = mpf(0)
        binom = 1
        for j in range(0, n):
            total += binom * p_pow[n - j] * q_pow[j] * g[j]
            binom = binom * (n - j) // (j + 1)
        g[n] = total
    return g


def a_infty(seq, log_m, inv_m, p, m_cut, n_max):
    """Windowed fundamental coefficient A_inf of a bounded solution,
    via the geometric subsequence t_min + kL and Aitken extrapolation.
    The window is kept above the index m_cut."""
    q = mpf(1) - p
    L = log(1 / q)
    omega = 2 * pi / L
    t_min = log(mpf(m_cut + 1)) + HALF_WIDTH * L
    t_max = log(mpf(n_max)) - (HALF_WIDTH + mpf(1) / 2) * L
    K = int(floor(float((t_max - t_min) / L)))
    if K < 2:
        return local_coefficient(seq, log_m, inv_m, t_max, L, omega, n_max)
    A = [local_coefficient(seq, log_m, inv_m, t_min + k * L, L, omega, n_max)
         for k in range(K + 1)]
    return aitken(A[-3], A[-2], A[-1])


def analyse(p_frac, m_cut, n_max):
    p = mpf(p_frac.numerator) / mpf(p_frac.denominator)
    q = mpf(1) - p
    L = float(log(1 / q))
    print(f"\n{'='*74}\n p = {p_frac} = {float(p):.4f}   q = {float(q):.4f}"
          f"   L = {L:.4f}   M = {m_cut}   n_max = {n_max}\n{'='*74}")

    log_m = [mpf(0)] + [log(m) for m in range(1, n_max + 1)]
    inv_m = [mpf(0)] + [mpf(1) / m for m in range(1, n_max + 1)]

    A_b = a_infty(b_sequence(n_max, p), log_m, inv_m, p, m_cut, n_max)
    print(f" A_inf(b)        = {complex(A_b):+.5e}"
          f"   |A| = {float(abs(A_b)):.3e}   arg = {float(arg(A_b)):+.4f}")
    print()

    Ar = []
    for r in range(m_cut + 1):
        g = basis_solution(n_max, p, m_cut, r)
        A = a_infty(g, log_m, inv_m, p, m_cut, n_max)
        Ar.append(A)
        print(f"   A_inf(e^({r:2d})) = {complex(A):+.5e}"
              f"   |A| = {float(abs(A)):.3e}   arg = {float(arg(A)):+.4f}")

    amax = max(float(abs(A)) for A in Ar)
    gens = [A for A in Ar if float(abs(A)) > 1e-3 * amax]
    angs = sorted(float(arg(A)) for A in gens)
    gaps = [angs[i + 1] - angs[i] for i in range(len(angs) - 1)]
    gaps.append(angs[0] + 2 * PI - angs[-1])
    maxgap = max(gaps)
    span = 2 * PI - maxgap
    pointed = maxgap > PI
    print(f"\n {len(gens)} non-negligible generators;"
          f"  angular span = {span:.4f} rad,  largest gap = {maxgap:.4f} rad")
    if pointed:
        print(" => generators lie in an OPEN HALF-PLANE: cone C is POINTED"
              " -- D2 holds for this M.")
    else:
        print(" => generators WIND AROUND the origin: cone C is NOT POINTED"
              " -- D2 is FALSE for this M.")
        print("    Then -A_inf(b) in C, and the cone argument for Gap D"
              " collapses.")
    return p_frac, Ar, A_b, pointed


def plot(results, out_path):
    n = len(results)
    fig, axes = plt.subplots(1, n, figsize=(5 * n, 5))
    if n == 1:
        axes = [axes]
    for ax, (p_frac, Ar, A_b, pointed) in zip(axes, results):
        for r, A in enumerate(Ar):
            z = complex(A)
            ax.annotate("", xy=(z.real, z.imag), xytext=(0, 0),
                        arrowprops=dict(arrowstyle="->", color="tab:blue",
                                        lw=1.0))
            ax.text(z.real, z.imag, f" {r}", fontsize=8, color="tab:blue")
        zb = complex(A_b)
        ax.annotate("", xy=(-zb.real, -zb.imag), xytext=(0, 0),
                    arrowprops=dict(arrowstyle="->", color="tab:red", lw=1.6))
        ax.text(-zb.real, -zb.imag, r"  $-A_\infty(b)$", color="tab:red",
                fontsize=9)
        ax.axhline(0, color="gray", lw=0.4)
        ax.axvline(0, color="gray", lw=0.4)
        ax.set_aspect("equal")
        verdict = "pointed (D2 holds)" if pointed else "NOT pointed (D2 false)"
        ax.set_title(f"p = {p_frac}:  cone C  --  {verdict}")
        ax.set_xlabel(r"$\Re$")
        ax.set_ylabel(r"$\Im$")
    plt.tight_layout()
    plt.savefig(out_path, dpi=140)
    print(f"\nwrote {out_path}")


def main():
    print("D2 test: is C = A_inf(non-negative solutions) a pointed cone?")
    print(f"(working precision {mp.dps} digits)")
    results = []
    for p_frac in [Fraction(2, 5), Fraction(3, 10)]:
        results.append(analyse(p_frac, M, N_MAX))
    plot(results, Path(__file__).parent / "d2_cone.pdf")
    print(f"\n{'='*74}")
    print(" Reading: if the blue generators A_inf(e^(r)) span < pi (one")
    print(" half-plane), C is pointed and D2 holds; if they wind around,")
    print(" D2 is false and -A_inf(b) (red) lies inside C.")
    print(f"{'='*74}")


if __name__ == "__main__":
    main()
