"""One-dimensional phase-1 model for the amplitude A_1(M).

Numerically, A_1(M) is generated by the future data on (M, M/q]
(future_data_amplitude.py).  There the gap gamma(n) := w_M - w_{n-1}
obeys, up to negligible terms,

   gamma(M+1) = 0,
   gamma(n+1) = (1 - P_n) gamma(n) + q^n W - s_n - p^n (1 - W),
   P_n = P(Bin(n,q) <= M),   s_n = older-record term.

The future gap is g_j = gamma(j+1) - gamma(inf) (= w_{M''} - w_j), and
r_n = -g_{n-1} (1 - P_n - q^n).  With  s_n = m q^{M+1} W rho^{n-M-1}
(m = marginality of the birth, rho = decay ratio of the older-record
term) the model depends only on (p, M, W, m, rho).  This script builds
the model data, evaluates A_1^model = -(1/L) Mellin[Pi T](2 pi i/L), and
compares with the true A_1(M).  Two variants: (a) s_n taken exactly from
the data, (b) geometric s_n from (m, rho).

Usage: python3 phase1_model_amplitude.py p M [Mprev]
"""
import sys, os
import mpmath as mp
from magic_numbers import run, records

ps = sys.argv[1]; M = int(sys.argv[2])
N = 700
mp.mp.dps = int(os.environ.get('DPS', 110))
MAXDEG = int(os.environ.get('MAXDEG', 5))
p = mp.mpf(ps); q = 1 - p; L = mp.log(1 / q)
w, b, _ = run(ps, N)
rec = [m for m in records(w, N) if m < N]
Mprev = int(sys.argv[3]) if len(sys.argv) > 3 else max(m for m in rec if m < M)
W = w[N]


def binom_cdf(n, K):
    t = p ** n; s = t
    for j in range(1, K + 1):
        t = t * (n - j + 1) / j * q / p; s += t
    return s


def s_exact(n):
    """older-record term sum_{j<=Mprev} omega_{n,j}(K_j - w_{n-1}), K_j = max_{[j,M]} w."""
    t = p ** n; s = mp.mpf(0)
    K = [None] * (Mprev + 1); cur = None
    for j in range(Mprev, 0, -1):
        cur = w[j] if cur is None else max(cur, w[j]); K[j] = cur
    for j in range(1, Mprev + 1):
        t = t * (n - j + 1) / j * q / p
        s += t * (K[j] - w[n - 1])
    return s


s1 = s_exact(M + 1); s2 = s_exact(M + 2)
m_marg = s1 / (q ** (M + 1) * w[M]); rho = s2 / s1
print(f"p={ps}, M={M}, Mprev={Mprev}: marginality m = {mp.nstr(m_marg,5)}, rho = {mp.nstr(rho,5)}, q = {mp.nstr(q,4)}, W = {mp.nstr(W,10)}")


def model_data(variant, nmax):
    gam = {M + 1: mp.mpf(0)}
    for n in range(M + 1, nmax):
        if variant == 'exact':
            sn = s_exact(n) if n - 1 <= N else mp.mpf(0)
        else:
            sn = m_marg * q ** (M + 1) * W * rho ** (n - M - 1)
        Pn = binom_cdf(n, M)
        gam[n + 1] = (1 - Pn) * gam[n] + q ** n * W - sn - p ** n * (1 - W)
    ginf = gam[nmax]
    g = {j: gam[j + 1] - ginf for j in range(M + 1, nmax)}
    r = {n: -g[n - 1] * (1 - binom_cdf(n, M) - q ** n) for n in range(M + 2, nmax)}
    return g, r


def Pi(u):
    out = mp.mpf(1); a = p * u / q
    while a < 400:
        out *= (1 - mp.exp(-a)); a /= q
    return out


def horner(c, u):
    out = mp.mpf(0)
    for a in reversed(c):
        out = out * u + a
    return out


def amplitude(g, r, J):
    cP = [mp.mpf(0)] * (J + 1); cR = [mp.mpf(0)] * (J + 1)
    for j in range(M + 1, J + 1):
        cP[j] = g.get(j, 0) * q ** j / mp.factorial(j)
        cR[j] = r.get(j, 0) / mp.factorial(j)
    T = lambda u: (1 - mp.exp(-p * u)) * mp.exp(-q * u) * horner(cP, u) + mp.exp(-u) * horner(cR, u)
    om = 2 * mp.pi / L
    f = lambda tau: Pi(mp.exp(tau)) * T(mp.exp(tau)) * mp.exp(-1j * om * tau)
    tmin = mp.log(M) - 3; tmax = mp.log(40 * J + 3000 / q)
    pts = mp.linspace(tmin, tmax, int((tmax - tmin) * 2) + 2)
    return -mp.quad(f, pts, maxdegree=MAXDEG) / L


nmax = int(3 * M / q)
J = int(2 * M / q)
for variant in ['exact', 'geometric']:
    g, r = model_data(variant, nmax)
    # compare model gaps with the true future gaps at a few j
    xinf = lambda j: max(w[k] for k in range(j, N + 1))
    chk = [(j, mp.nstr(g[j] / q ** M, 4), mp.nstr((xinf(j) - w[j]) / q ** M, 4)) for j in [M + 1, M + 2, M + 5, int(M / q)] if j <= N]
    A1 = amplitude(g, r, J)
    print(f"  variant {variant:9s}: g_j/q^M (model, true) at j = {chk}")
    print(f"     |A1^model| = {mp.nstr(abs(A1),6)},  |A1^model|/q^M = {mp.nstr(abs(A1)/q**M,6)}")
